### ISSUE TITLE
hecatomb.config.yaml

### ISSUE THREAD

**Issue by wuhuiyun07** [shandley/hecatomb#108]
In my hecatomb.config.yaml the path is
    conda_prefix: /usr/local/lib/python3.12/site-packages/hecatomb/snakemake/conda.
How can I modify this path and how can I define it?

Error message:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/snakemake/__init__.py", line 792, in snakemake
    success = workflow.execute(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake/workflow.py", line 842, in execute
    self._persistence = Persistence(
                        ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake/persistence.py", line 111, in __init__
    os.makedirs(d, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.12/site-packages/hecatomb/snakemake/conda'

**Comment by wuhuiyun07** [comment]
Issue solved. I download a docker image and it was not working. I followed the conda installation and it worked.
